---

- name: Copying a file from local to remote hosts using #### copy module #####
  ansible.builtinfile.copy:
     src: file_copy_1
     dest: /tmp/
     owner: ansi
     mode: '0600'

- name: Copying file from remote to local using #### Fetch module ##############
  ansible.builtin.fetch:
     src: "/etc/fstab"
     dest: "backups/{{ inventory_hostname }}/"
     flat: yes

- name: Copying file from remote to local using #### Fetch methhod 2 ############
  ansible.builtin.fetch:
     src: "/etc/hosts"
     dest: "backups/fstab.{{ inventory_hostname }}.{{ ansible_date_time.date }}"
     flat: yes
