---

- name: Creating a local user in ansible host
  ansible.builtin.user:
     name: "{{ local_user1 }}
     state: present
  delegate_to: "{{ local_host_ansible }}"
     

- name: creating a ssh-key for a user
  ansible.builtin.user:
     name: "{{ local_user1 }}"
     generate_ssh_key: yes
     ssh_key_bits: 2048
     ssh_key_file: .ssh/id_rsa.pub
  delegate_to: "{{ local_host_ansible }}"

- name: copying ssh to all nodes
  ansible.builtin.authorized_key:
     name: "{{ local_user1 }}
     state: present
     key: "{{ lookup('file', '/home/{{ local_user1 }}/.ssh/id_rsa.pub') }}"
