---

- name: Generating unix password for local users.
  ansible.builtin.shell: pwgen -s -1 -y 16
  register: unix_user_pass
- debug:
     var: unix_user_pass.stdout

- name: Changing root password on all hosts
  ansible.builtin.user:
     name: "{{ item }}"
     password: "{{ unix_user_pass.stdout | password_hash('sha512') }}"
  loop: "{{ usr_roles }}"
