---
- name: admin tasks new
  hosts: full
<<<<<<< HEAD
 
=======
>>>>>>> bcbdecc (new structure of roles)
  vars_files:
    - vars/creation_user_grp.yml
    - vars/user_details.yml
  tasks:
    - name: user group creation and password set
      import_tasks:
        file: tasks/usergroup.yml
<<<<<<< HEAD

=======
>>>>>>> bcbdecc (new structure of roles)
